# Generated by Django 3.2.7 on 2021-09-13 05:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='index')),
                ('imdb_id', models.CharField(max_length=255, null=True, verbose_name='imdb_id')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('genres', models.CharField(max_length=255, null=True, verbose_name='genres')),
                ('poster_path', models.CharField(max_length=255, null=True, verbose_name='poster_path')),
                ('release_date', models.CharField(max_length=255, null=True, verbose_name='release_date')),
                ('runtime', models.FloatField(null=True, verbose_name='runtime')),
                ('vote_average', models.FloatField(null=True, verbose_name='vote_average')),
            ],
        ),
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
