# Generated by Django 3.2.7 on 2021-10-31 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211027_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrating',
            name='userId',
        ),
    ]
