# Generated by Django 3.2.7 on 2021-11-01 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_userrating_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrating',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
